(function() {
  var Schema, app, auth, config, env, express, fs, mongoose, passport, port;
  express = require('express');
  fs = require('fs');
  passport = require('passport');
  require('express-namespace');
  env = process.env.NODE_ENV || "development";
  config = require('./config/config')[env];
  auth = require('./authorization');
  mongoose = require('mongoose');
  Schema = mongoose.Schema;
  mongoose.connect(config.db);
  require("./app/models/user");
  require("./app/models/issue");
  require("./app/models/org");
  require("./app/models/repository");
  require("./config/passport").boot(passport, config);
  app = express();
  require("./settings").boot(app, config, passport);
  require("./config/routes")(app, passport, auth);
  port = process.env.PORT || 3000;
  app.listen(port);
  console.log("Express app started on port " + port);
}).call(this);
